version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: attendance_system
    ports:
      - "3306:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
